# server has three main properties:
# port : udserver port, default is 60001
# uuid_path : each udserver has a unique id, uuid file will be created automatically
#             when the first run
# timeout : for each client connection, set the read timeout. default 300 seconds
# type : mapper or reducer

server: 
    port: 9700
    uuid_path: etc/id.uuid
    timeout: 300
    type: mapper
    mrhandler: com.ambimmort.rmr.server.SimpleMapper
    collector: 
        className: com.ambimmort.rmr.plugins.collector.PrintCollector
        paras:
            file: C:/Users/定巍/Desktop/collector.txt
            ips:
                - 10.8.1.1
                - 10.8.1.1
                
#    type: reducer
#    mrhandler: com.ambimmort.rmr.SimpleReducer
#    collector: 
#        className: com.ambimmort.sd.PrintCollector
#        paras:
#            file: C:/Users/定巍/Desktop/collector.txt
#            ips:
#                - 10.8.1.1
#                - 10.8.1.1

cache: 
    limit: 1000
    period: 20
    threads_max: 50
    check_interval: 1

log:
    logcodec: false
    logconfigfile: etc/log4j.conf